#!/usr/bin/env bash

# modified @nixcasts flashcard script
# https://www.youtube.com/watch?v=lX8jqo70r1I
#
# Date: 2022-12-25
#
# Author: Sean Burns <sean.csb@gmail.com>

set -e

clear

trap quit 1 2 3 6

quit() {
	echo -e "\n\nThanks for playing and learning.\n"
	exit
}

proceed() {
	read -rp "Press enter to continue or press Ctrl-c (control and the 'c' keys) to exit."
	clear
}

cat <<-EOF

This is flashcard like program to help you remember an assortmant of commands.

To play:

You will be presented with a question.

To answer, type the name of the command in response to the question.

Read more about the commands in their man pages.

EOF

proceed

# Help with SCRIPT_DIR variable to generalize the location of the cards.csv file came from:
# https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
FILE="$SCRIPT_DIR/cards.csv"

main() {
	# underline=$(tput smul)
	# normal=$(tput sgr0)
	IFS=$','; read -ra card <<<"$(shuf -n 1 "$FILE")"
	printf "\nQuestion: %s\n" "${card[0]}"
	read -rp "Your answer: " answer
	printf "\n"
}

checkanswer() {
	green=$(tput setaf 2)
	red=$(tput setaf 1)
	normal=$(tput sgr0)
	if [ "$answer" = "${card[1]}" ] ; then
		printf "%s" "${green}Correct!${normal}"
		printf "\n\n"
		printf "The correct answer is: %s" "$underline${card[1]}$normal"
		printf "\n\n"
	else
		printf "%s" "${red}Incorrect. Keep trying!${normal}"
		printf "\n\n"
		printf "The correct answer is: %s" "$underline${card[1]}$normal"
		printf "\n"
	fi
}

while true; do
	main
	checkanswer
	proceed
done
